[package]
name = "mwc713"
version = "2.2.0"
authors = ["vault713 devs"]
description = "A wallet that makes it easy to send, store, and swap MWC."
keywords = [ "grin", "mimblewimble", "rust", "crypto", "cryptocurrency" ]
license = "Apache-2.0"
readme = "README.md"

[dependencies]
serde = "1.0"
dont_disappear = "3.0.0"
serde_derive = "1.0"
serde_json = "1.0"
toml = "0.4"
clap = "2"
ansi_term = "0.11"
colored = "1.6"
ws = { version = "0.8", features = ["nativetls"] }
native-tls = { version = "0.2", features = ["vendored"] }
dirs = "1"
futures = "0.1"
tokio = "= 0.1.22"
rand = "0.5"
sha2 = "0.7"
digest = "0.7"
lmdb-zero = "0.4"
failure = "0.1"
uuid = { version = "0.6", features = ["serde", "v4"] }
regex = "1"
rustyline = "5.0"
hmac = "0.6"
ripemd160 = "0.7"
ring = "0.13"
prettytable-rs = "0.7"
gotham = "0.3.0"
gotham_derive = "0.3.0"
hyper = "0.12"
mime = "0.3"
chrono = { version = "0.4.4", features = ["serde"] }
blake2-rfc = "0.2"
log = "0.4"
env_logger = "0.6.0"
rpassword = "2.1.0"
url = "1.7"
parking_lot = {version = "0.6"}
semver = "0.9.0"
commands = "0.0.5"
enquote = "1.0"
reqwest = "0.9.20"

grin_api = { git = "https://github.com/mwcproject/mwc-node", tag="2.3.3"}
grin_core = { git = "https://github.com/mwcproject/mwc-node", tag="2.3.3"}
grin_keychain = { git = "https://github.com/mwcproject/mwc-node", tag="2.3.3"}
grin_util = { git = "https://github.com/mwcproject/mwc-node", tag="2.3.3"}
grin_store = { git = "https://github.com/mwcproject/mwc-node", tag="2.3.3"}
grin_p2p = { git = "https://github.com/mwcproject/mwc-node", tag="2.3.3"}
